name: Shell Commands
on: [push]
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo 'Hello world!'
      - name: multiline script
        run: |
          node --version
          npm --version
  run-windows-command:
    needs: ["run-shell-command"]
    runs-on: windows-latest
    steps:
      - name: Directory PowerShell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash
